### ISSUE TITLE
ambiguous syntaxes

### ISSUE THREAD

**Issue by royling** [tc39/proposal-partial-application#10]
When mixing `?` and `...` tokens, I guess only a set of syntaxes are valid imaging how the parser is going to work. Would you mind confirming the validity of the following syntaxes?

```js
const f = (...x) => x

const g = f(?, 0, ..., ?) // valid?
const h = f(..., ?, 0, ...) // invalid? seems ambiguous
```

**Comment by rbuckton** [comment]
Originally, I intended the above to be approximately the same as this:

```js
const g = (a, b, ...c) => f(a, 0, ...c, b);
const h = (a, ...b) => f(...b, a, 0, ...b);
```

However, following discussions at the September TC39 meeting, I think the following restriction makes sense:

* Neither `?`, nor `...` may follow `...` in an argument list.

That would make both `g` and `h` above an error, though we could loosen this restriction slightly if we implement #5.

**Comment by rbuckton** [comment]
Closing as `...` is currently disallowed as of the latest draft of this proposal.
