### ISSUE TITLE
Consider adding "positional" placeholders

### ISSUE THREAD

**Issue by rbuckton** [tc39/proposal-partial-application#5]
A "positional" placeholder allows you to specify the ordinal position of the parameter in the 
partially applied function result to supply to the current argument. Positional placeholders
allow you to swap arguments and reuse the same argument more than once.

# Syntax
```js
f(?0)       // pass argument 0:         x => f(x)
f(?0, ?0)   // pass argument 0 twice:   x => f(x, x)
f(?1)       // pass argument 1:         (_, x) => f(x)
f(?1, ?0)   // swap arguments:          (x, y) => f(y, x)
```

# Semantics

* Given `g = f(?0)`, function `g` has a single parameter that is passed to `f` as the first argument.
* Given `g = f(?0, ?0)`, function `g` has a single parameter that is passed to `f` as its first and second arguments.
* Given `g = f(?1)`, function `g` has two parameters. The first is unused and the second is passed to `f` as the first argument.
* Given `g = f(?0, ?1)`, function `g` has two parameters. The second argument of `g` is passed to `f` as the first argument and the first argument of `g` is passed to `f` as the second argument.

# Grammar
```js
ArgumentList[Yield, Await]:
  `?` DecimalIntegerLiteral?
  AssignmentExpression[+In, ?Yield, ?Await]
  `...` AssignmentExpression[+In, ?Yield, ?Await]?
  ArgumentList[?Yield, ?Await] `,` `?` DecimalIntegerLiteral?
  ArgumentList[?Yield, ?Await] `,` AssignmentExpression[+In, ?Yield, ?Await]
  ArgumentList[?Yield, ?Await] `,` `...` AssignmentExpression[+In, ?Yield, ?Await]?
```

I did not add this to the proposal as it adds additional complexity that may not be worth including at this time.

**Comment by Jamesernator** [comment]
What should it do with `...` if arguments are not used?

e.g.

```js
f(?0, ?2, ...) // No ?1 but there's a spread, is arg 1 in the spread
               // or just 3 onwards
```

**Comment by rbuckton** [comment]
It would add a synthetic second argument, and behave like: `(x, _, y, ...z) => f(x, y, ...z)`.

**Comment by dangerousdan** [comment]
Note that this is similar to how regex substrings work. (Although, annoyingly, regex substring indexes start at 1).

```javascript
"foo bar!".replace(/([a-z]+) ([a-z]+)/, '$2 $1')// returns "bar foo!"
```

I'd argue as well that issue #21 (Too much question mark) is even more applicable with positional placeholders, as we're now even similar to a ternary operator.
