### ISSUE TITLE
Change to behave like Function.prototype.bind

### ISSUE THREAD

**Issue by gilbert** [tc39/proposal-partial-application#6]
First of all, nice proposal. I think it will be very useful.

You may be aware of this, but I want to give it an official issue. I think the currently proposed transformation...

```js
const g = f(10, ?)
//=>
const g = (_) => f(10, _)
```

...is unintuitive, since it relies on the **variable binding** of `f`. As you recognize, changing `f` will change the behavior of `g`. This will probably cause a lot of confusion, without much benefit.

Instead, I believe this new syntax should work like an enhanced `Function.prototype.bind`:

```js
const g = f.bind(null, 10)
```

`bind` creates a new function value independent of the variable; changing `f` will not change `g` in this scenario. Of course, the limitation of bind is that you can only apply arguments from left to right. This new proposal can be a fix to that limitation.

To behave this way, everything must be eagerly evaluated. This ends up being more intuitive anyway.

For completeness, the proposal would handle `this` values eagerly as well:

```js
const g = this.f(20, ?)
//=> roughly:
const g = f.bind(this, 20)
```

**Comment by rbuckton** [comment]
I've been discussing this with others about whether we should leverage "call-by-name" semantics vs. "call-by-value" semantics. There are languages with similar features on both sides of the divide. We've been discussing this in #1 as well.

**Comment by ljharb** [comment]
Given the following:
```js
let f = () => 1;
const g = f(1, ?);
f = () => 2;

// which one passes?
assert(g() === 1);
assert(g() === 2);
```

I think it would be very confusing if the second one passed - if I want to preserve the *binding* of `f`, instead of the value, i'd do `const g = x => f(1, x)` and not need any new syntax for it.

**Comment by rbuckton** [comment]
This is a good question for the committee as a whole. Currently it is specified as call-by-name, but that is obviously not set in stone. In an offline discussion with @danielrosenwasser it came up that Scala's `_` (which can be used in a fashion similar to the proposed `?` token) appears to delay computation entirely.

The main reason the strawman uses call-by-name and delays evaluation is that you can emulate call-by-value using local variables:

```js
let f = () => 1;
const t1 = f;
const g = t1(1, ?);
```

However, you cannot emulate call-by-name using call-by-value semantics, at least not with this proposal.

**Comment by TiddoLangerak** [comment]
FWIW: existing user-land implementations of partial application are (almost?) all call-by-value (I don't think it's even possible to make a sane user-land implementation that is call-by-name). I therefore think that the majority of JS developers would expect call-by-value semantics, not call-by-name semantics. It is therefore also much easier to migrate from a lib to native if native is call-by-value.

**Comment by gilbert** [comment]
I agree with @TiddoLangerak in that call-by-value is more intuitive because it's natural to see function arguments and assume they will execute immediately. 

I should add, if one wants call-by-name semantics, it's not hard to use an arrow function. Call-by-name seems only useful when you're writing a non-one-off function anyway, the type of function this proposal shines at.

Can anyone think of practical use cases for call-by-name that would greatly benefit from this proposal?

**Comment by vadzim** [comment]
I think it could be useful first to decide using of which thing we want to make more comfortable - either arrow functions or .bind function.
IMHO arrow functions are already expressive enough and they do not need other improvements.
On the other hand .bind is too limited - it allows to fix only arguments at the beginning.
So I believe it'd be better to implement call by value semantics.

**Comment by vadzim** [comment]
Also call by value together with pipe line operator will make [function bind](https://github.com/tc39/proposal-bind-operator) proposal unneeded and so will preserve the language syntax simpler.
I mean that `x.y(...)` will be equal to `::x.y` and to `x.y.bind(x)`

**Comment by rbuckton** [comment]
Closing this issue as the current semantics specify eager evaluation, which aligns with the behavior of `Function#bind`.
