### ISSUE TITLE
Prior art/reference: `param.macro`

### ISSUE THREAD

**Issue by citycide** [tc39/proposal-partial-application#8]
_update_: I've created a new project [`param.macro`](https://github.com/citycide/param.macro) for partial application (and lambda parameters) to replace the one mentioned here. It's more focused and stable, and drops the more outlandish features. You might want to read the [introductory post](https://medium.com/@citycide/partial-application-lambda-parameters-for-js-aa16f4d94df4) and check out the online playground at https://citycide.github.io/param.macro.

It might be useful as an approximation while the proposal works its way into Babel and beyond.

```js
import { _ } from 'param.macro'
const add = (x, y) => x + y
const addOne = add(_, 1)
addOne(9)
// -> 10
```

---

<details>
<summary>original post</summary>
Would love to see this make it in syntactically! I built a Babel plugin ( [babel-plugin-partial-application](https://github.com/citycide/babel-plugin-partial-application) ) that allows for syntactic-esque partial application using `_` or a custom token - obviously due to back compat that's not possible for a native feature. I think it might be a useful reference for this proposal.

Right now it supports ( copied from readme ):

- basic placeholders: `add(1, _)`
- spread placeholders: `Math.max(..._)`
- object placeholders: `_.hasOwnProperty('dapper')`
- lambda parameters: `people.map(_.name)`
- positional placeholders: ``const isSameThing = _`1` === _`1` ``
- binary expressions: `_ === 'awesome'`, `_.getPower().level > 9000`
- default parameters: `const stringify = JSON.stringify(_, null, _ = 2)`
- template literals: ``const greet = `Hello, ${_}!` ``
- set a custom token: `import _ from 'babel-plugin-partial-application'`

You can try it out online at https://citycide.github.io/babel-plugin-partial-application ( short URL https://git.io/bp-partial ) if you want to test out any of the features.
</details>

**Comment by rbuckton** [comment]
I do not believe this would sufficiently warrant a reference as prior art unless this project sees significant usage within the community.
